// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// WordFactory is an autogenerated mock type for the WordFactory type
type WordFactory struct {
	mock.Mock
}

// GenerateWordList provides a mock function with given fields: numOfWords
func (_m *WordFactory) GenerateWordList(numOfWords int) []string {
	ret := _m.Called(numOfWords)

	var r0 []string
	if rf, ok := ret.Get(0).(func(int) []string); ok {
		r0 = rf(numOfWords)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}
