// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// WordHint is an autogenerated mock type for the WordHint type
type WordHint struct {
	mock.Mock
}

// GiveHint provides a mock function with given fields: word
func (_m *WordHint) GiveHint(word string) string {
	ret := _m.Called(word)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(word)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
