// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	identifier "github.com/bseto/arcade/backend/websocket/identifier"
	mock "github.com/stretchr/testify/mock"
)

// WebsocketCloseListener is an autogenerated mock type for the WebsocketCloseListener type
type WebsocketCloseListener struct {
	mock.Mock
}

// WebsocketClose provides a mock function with given fields: clientID
func (_m *WebsocketCloseListener) WebsocketClose(clientID identifier.Client) {
	_m.Called(clientID)
}
