// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	websocket "github.com/bseto/arcade/backend/websocket"
	mock "github.com/stretchr/testify/mock"
)

// WebsocketClient is an autogenerated mock type for the WebsocketClient type
type WebsocketClient struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *WebsocketClient) Close() {
	_m.Called()
}

// Dial provides a mock function with given fields: hostname
func (_m *WebsocketClient) Dial(hostname string) {
	_m.Called(hostname)
}

// RegisterCloseListener provides a mock function with given fields: listener
func (_m *WebsocketClient) RegisterCloseListener(listener websocket.WebsocketCloseListener) {
	_m.Called(listener)
}

// Upgrade provides a mock function with given fields: w, r
func (_m *WebsocketClient) Upgrade(w http.ResponseWriter, r *http.Request) error {
	ret := _m.Called(w, r)

	var r0 error
	if rf, ok := ret.Get(0).(func(http.ResponseWriter, *http.Request) error); ok {
		r0 = rf(w, r)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
